import Sessionwrapper from "./components/sessionwrapper";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const navbar = <nav>
  <div className="nav  text-lg">
    <ul className="ms-3">
        <Link href="/home"><li className="hover:scale-103 transition-transform duration-1000">Home</li></Link>
        <li className="hover:scale-103 transition-transform duration-1000">Tools</li>
        <li className="hover:scale-103 transition-transform duration-1000">Categories</li>
        <Link href="/users"><li className="hover:scale-103 transition-transform duration-1000">Users</li></Link>
    </ul>
              
    <Image 
    src="/userimg.png"
    alt="User Image"
    className="userimage ms-auto me-3 my-auto "
    height={100}
    width={50}
    />

  </div>
</nav>


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {navbar}
        <Sessionwrapper>{children}</Sessionwrapper>
      </body>
    </html>
  );
}
